const prefixesByType = {
    'FIRE': ['blaze', 'flame', 'ember', 'inferno', 'scorch', 'cinder', 'ignite', 'pyre', 'firestorm', 'heat'],
    'ICE': ['frost', 'ice', 'shiver', 'glacier', 'blizzard', 'frozen', 'icicle', 'chill', 'polar', 'cryostorm'],
    'WIND': ['gale', 'breeze', 'wind', 'storm', 'zephyr', 'whirlwind', 'aero', 'cyclone', 'tempest', 'tornado'],
    'WATER': ['aqua', 'ripple', 'tidal', 'current', 'cascade', 'hydro', 'deluge', 'aquatic', 'whirlpool', 'marine'],
    'EARTH': ['stone', 'rock', 'earth', 'boulder', 'crystal', 'terra', 'quartz', 'geode', 'petra', 'magma'],
    'ELECTRIC': ['shock', 'spark', 'jolt', 'volt', 'electra', 'charge', 'thunder', 'zap', 'surge', 'electrum'],
    'SOLAR': ['solar', 'sun', 'luminar', 'flare', 'stellar', 'radiant', 'celestial', 'solaris', 'daybreak', 'sunburst'],
    'LUNAR': ['luna', 'moon', 'night', 'shadow', 'eclipse', 'lunar', 'noctis', 'twilight', 'gloam', 'umbral'],
    'SHADOW': ['shade', 'shadow', 'umbra', 'phantom', 'dark', 'dusk', 'veil', 'silhouette', 'shroud', 'nightfall'],
    'MYSTIC': ['mystic', 'enigma', 'arcane', 'ethereal', 'sorcery', 'mystique', 'oracle', 'charisma', 'elixir', 'spell'],
    'NATURE': ['nature', 'flora', 'sylvan', 'blossom', 'verde', 'thorn', 'vitalis', 'arbor', 'petal', 'folium'],
    'ASTRAL': ['astral', 'celestial', 'stellar', 'cosmic', 'galactic', 'luminar', 'radiant', 'aurora', 'eclipsar', 'supernova'],
    'TOXIC': ['toxic', 'venom', 'poison', 'contagion', 'noxious', 'radioactive', 'toxica', 'plague', 'vile', 'malady'],
    'METALLIC': ['metallic', 'iron', 'steel', 'bronze', 'titanium', 'chrome', 'alloy', 'brass', 'silver', 'gold'],
    'SPECTRAL': ['spectral', 'ghostly', 'phantom', 'wraith', 'ethereal', 'apparition', 'haunting', 'poltergeist', 'soulbound', 'unearthly'],
    'CHAOS': ['chaos', 'disorder', 'entropy', 'pandemonium', 'anarchy', 'turmoil', 'mayhem', 'havoc', 'discord', 'cacophony'],
    'VOID': ['void', 'abyss', 'nihil', 'null', 'abyssal', 'voidborn', 'nullify', 'obliterate', 'annihilate', 'eradicate'],
};

const genericSuffixes = [
    'King',
    'Queen',
    'Master',
    'Finder',
    'Guardian',
    'Seeker',
    'Champion',
    'Sorcerer',
    'Warrior',
    'Mage',
    'Hunter',
    'Savior',
    'Protector',
    'Harbinger',
    'Inferno',
    'Bane',
    'Ranger',
    'Avenger',
    'Warden',
    'Sentinel',
    'Summoner',
    'Oracle',
    'Specter',
    'Paragon',
    'Dreadlord',
    'Patriarch',
    'Matriarch',
    'Conqueror',
    'Shadow',
    'Blaze',
    'Thunder',
    'Frost',
    'Flame',
    'Storm',
    'Fury',
    'Whisper',
    'Wanderer',
    'Eclipse',
    'Gaze',
    'Emissary',
    'Throne',
    'Warden',
    'Rogue',
    'Spirit',
    'Monarch',
    'Elemental',
    'Exile',
    'Noble',
    'Vanguard',
    'Wraith',
    'Phantom',
    'Chalice',
    'Pinnacle',
    'Crest',
    'Vortex',
    'Infinity',
    'Zenith',
    'Saga',
    'Voyager',
    'Abyss',
    'Goddess',
    'Titan',
    'Archon',
    'Pioneer',
    'Sovereign',
    'Ascendant',
    'Epoch',
    'Sentinel',
    'Pulse',
    'Quasar',
    'Eon',
    'Pioneer',
    'Catalyst',
    'Lorekeeper',
    'Prodigy',
    'Celestial',
    'Adept',
    'Aegis',
    'Vanquisher',
    'Aether',
    'Crusader',
    'Ethereal',
    'Eclipse',
    'Nebula',
    'Nemesis',
    'Scepter',
    'Sculptor',
    'Emissary',
    'Nexus',
    'Monolith',
    'Herald',
    'Cynosure',
    'Pyre',
    'Ember',
    'Dusk',
    'Equinox',
    'Chronicle',
];

export { prefixesByType, genericSuffixes}

